name: Time to Bake...

on: 
  #releasepush:
    #pushbuild

  watch: 
      types: [started]
    
env:
  ROM_URL: https://mirrors.lolinet.com/firmware/lenovo/l79031/L79031_ROW_SECURE_USER_Q00094.1a_Q_ROW_12.0.073_ST_200702_qpst.zip
  ROM_NAME: Generic:ZUI
  ZIP_NAME: ZUI-Helios
  TZ: Middle-East/Kuwait

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@main
       
           
       - name: Setting up the workflow 
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python3
            sudo -E apt-get -qq install simg2img
       
       - name: processing ErfanGSIs code 
         run: git clone --recurse-submodules https://github.com/123ridhin/ErfanGSIs.git
       
       - name: Setting up requirements and permissions
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zipping Aonly
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img
             
       - name: uploading Aonly.zip
         run: |    
              curl -sL https://git.io/file-transfer | sh
              ./transfer cow ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z 
                       
       - name: Zipping AB
         run: |
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              
       - name: uploading AB.zip
         run: |
              ./transfer cow ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z      
              
       - name: Upload Build Informations and Baked:)
         run: |
              ./transfer cow ErfanGSIs/output/*-Aonly-*.txt
         

                                                  

  
         
     
