name: Time to Bake...

on: [push]


  watch:
    types: [started]
    
env:
  ROM_URL: http://download.h2os.com/5T/MP/OnePlus5THydrogen_43_OTA_062_all_2005291737_04f9b97b5ae84d67.zip
  ROM_NAME: OxygenOS:HydrogenOS
  ZIP_NAME: HydrogenOS-Helios
  TZ: Middle-East/Kuwait

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Setting up the workflow 
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python3
            sudo -E apt-get -qq install simg2img
       
       - name: processing ErfanGSIs code 
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Setting up requirements and permissions
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zipping Aonly
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img
             
       - name: uploading Aonly.zip
         run: |    
              curl -sL https://git.io/file-transfer | sh
              ./transfer gof ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z 
                       
       - name: Zipping AB
         run: |
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              
       - name: uploading AB.zip
         run: |
              ./transfer gof ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z      
              
       - name: Upload Build Informations
         run: |
              ./transfer gof ErfanGSIs/output/*-Aonly-*.txt
              
       - name: Baked:)      
         run: sudo rm -rf ErfanGSIs
