name: Time to Bake...

on: 
  #releasepush:
    #pushbuild

  watch: 
      types: [started]
    
env:
  ROM_URL: wget --load-cookies /tmp/cookies.txt "http://tdrive.manofuranium.workers.dev/OnePlus6Oxygen_22_OTA_047_all_2007191515_d9e52461.zip(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1neT6AyCDh1XmexKLZ7gjLxn5ZVbSvkrx' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1neT6AyCDh1XmexKLZ7gjLxn5ZVbSvkrx" -O Motorola_Moto_G_Fast_XT2045-3_RAV_RETUS_10_QPJ30.131-16_10_(by_motostockrom.com).zip && rm -rf /tmp/cookies.txt
  ROM_NAME: Generic:Oxygen
  ZIP_NAME: Oxygen-Helios
  TZ: Middle-East/Kuwait

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@main
       
           
       - name: Setting up the workflow 
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python3
            sudo -E apt-get -qq install simg2img
       
       - name: processing ErfanGSIs code 
         run: git clone --recurse-submodules https://github.com/123ridhin/ErfanGSIs.git
       
       - name: Setting up requirements and permissions
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zipping Aonly
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img
             
       - name: uploading Aonly.zip
         run: |    
              curl -sL https://git.io/file-transfer | sh
              ./transfer cow ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z 
                       
       - name: Zipping AB
         run: |
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              
       - name: uploading AB.zip
         run: |
              ./transfer cow ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z      
              
       - name: Upload Build Informations and Baked:)
         run: |
              ./transfer cow ErfanGSIs/output/*-Aonly-*.txt
         

                                                  

  
         
     
