name: Time to Bake...

on: 
  #releasepush:
    #pushbuild

  watch: 
      types: [started]
    
env:
  ROM_URL: https://phoenixnap.dl.sourceforge.net/project/randomroms-testing-dontflash/potato_whyred-11-20200922-d.v4.0.0-staging%2B1.Community.zip
  ROM_NAME: Generic:POSP
  ZIP_NAME: POSP-HELIOS
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Middle-East/Kuwait
  MIR_NAME1: gof
  SFDIRA: cd /home/pfs/project/helios-gsis/OxygenOS
  
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@main
       
           
       - name: Setting up the workflow 
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python3
            sudo -E apt-get -qq install simg2img
       
       - name: processing ErfanGSIs code 
         run: git clone --recurse-submodules https://github.com/issacabraham-git/ErfanGSIs.git
       
       - name: Setting up requirements and permissions
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/gsi.sh $ROM_URL $ROM_NAME
       
       - name: Zipping Aonly
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img
         
       - name: Uploading to SFG
         run: spawn sftp ridhin@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-Aonly.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"  
             
       - name: uploading to MIR1 and MIR2 Aonly.zip 
         run: |    
              curl -sL https://git.io/file-transfer | sh
              ./transfer $MIR_NAME1 ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z
               
                     
       - name: Zipping AB
         run: |
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              
       - name: uploading to MIR1
         run: |
              ./transfer $MIR_NAME1 ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z 
                 
              
       - name: Upload Build Informations and Baked:)
         run: |
              ./transfer $MIR_NAME1 ErfanGSIs/output/*-Aonly-*.txt
         

                                                  

  
         
     
