name: Time to Bake...

on: 
  #releasepush:
    #pushbuild

  watch: 
      types: [started]
    
env:
  ROM_URL: https://dllb2.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE1OTgzNzYyODMiLCJ1IjpudWxsLCJsdCI6ImRvd25sb2FkIiwicyI6IjkxMjBiNjdmNjVmMGM0OTBmMmU5MjllMjc2MWM2YjM3MDZlZmZhZjg4NjM4YWJkMTdkMDJhNDIwMzA3M2Y5N2Y2NTViNGI4MDBkOWMzOTU3NTMzZDc2OWFmMDk5MmEyOWM3YmE5NTU2MjlkNmRjYTQzZGVmMGNkY2M1MWNlNzhlIiwidCI6MTU5ODU0MjY0Niwic3RmcCI6IjUxMmRlNTQzM2IxMWFjMmZjYzAxZmM2OWEyOTZmMmJmIiwic3RpcCI6IjE4OC43MS4yMzcuNjcifQ.foeJzmkm2FQt6464SYj80YfhxHyrl1iRrTtlx3f0YdI/ZenUI%206%20-%20August%20Update%20Port%20(Fixed).zip
  ROM_NAME: ZenUI
  ZIP_NAME: ZenUI-Helios
  TZ: Middle-East/Kuwait
  MIR_NAME1: wet

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@main
       
           
       - name: Setting up the workflow 
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python3
            sudo -E apt-get -qq install simg2img
       
       - name: processing ErfanGSIs code 
         run: git clone --recurse-submodules https://github.com/123ridhin/ErfanGSIs.git
       
       - name: Setting up requirements and permissions
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zipping Aonly
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img
             
       - name: uploading to MIR1 and MIR2 Aonly.zip 
         run: |    
              curl -sL https://git.io/file-transfer | sh
              ./transfer $MIR_NAME1 ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z
               
                     
       - name: Zipping AB
         run: |
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              
       - name: uploading to MIR1
         run: |
              ./transfer $MIR_NAME1 ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z 
                 
              
       - name: Upload Build Informations and Baked:)
         run: |
              ./transfer $MIR_NAME1 ErfanGSIs/output/*-Aonly-*.txt
         

                                                  

  
         
     
